server:
  port: ${SPRING_DOCKER_PORT}
spring:
  datasource:
    username: ${MYSQLDB_USER}
    password: ${MYSQLDB_ROOT_PASSWORD}
    url: ${DB_URL}
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: ${SHOW_SQL}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}
  application:
    name: ${APPLICATION_NAME}
  devtools:
    restart:
      enabled: ${DEV_TOOLS}
logging:
  level:
    web: ${WEB_LOGGING}


# Messages for exception
user:
  not:
    found: "user is not available. please try again"
